INSERT INTO contas (nome) VALUES ('Amazon') ON CONFLICT DO NOTHING;
INSERT INTO contas (nome) VALUES ('TotalExpress') ON CONFLICT DO NOTHING;
INSERT INTO contas (nome) VALUES ('Loggi') ON CONFLICT DO NOTHING;
INSERT INTO contas (nome) VALUES ('IMILE') ON CONFLICT DO NOTHING;
